# Generated by Django 4.2.5 on 2023-09-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_user'),
        ('products', '0003_alter_orderupdate_order_id'),
    ]

    operations = [
    ]
